"""Add selected_document_type column to app_settings

Revision ID: 4f669dcc8bff
Revises: 
Create Date: 2025-06-01 14:40:38.503838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f669dcc8bff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('selected_document_type', sa.String(length=100), nullable=True))
    op.drop_constraint('unique_prompt', 'prompts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_prompt', 'prompts', ['department', 'document_type', 'doctor'])
    op.drop_column('app_settings', 'selected_document_type')
    # ### end Alembic commands ###
